name: $(Rev:rrrrr)
pool:
  name: CSG OnPrem VS2019
trigger:
- master
- rel/*
steps:
- task: PowerShell@1
  displayName: 'Build'
  inputs:
    scriptName: build.ps1
    arguments: '-BuildNumber $(Build.BuildNumber) -NoTest'
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: 'tests\**\*Tests.csproj'
    arguments: '--no-build --configuration Release'
    verbosityPack: Minimal
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: nupkgs'
  inputs:
    PathtoPublish: 'bin\Release'
    ArtifactName: nupkgs
